/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import java.awt.Color;
import javax.swing.ImageIcon;
/**
 *
 * @author guich
 */
public class interfazCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfazCalculadora.class.getName());

    /**
     * Creates new form interfazCalculadora
     */
    public interfazCalculadora() {
        initComponents();
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/iconos/iconoCalculadora.png")).getImage());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_operacion = new javax.swing.JLabel();
        lbl_resultado = new javax.swing.JLabel();
        tb_claro_oscuro = new javax.swing.JToggleButton();
        panel_2 = new javax.swing.JPanel();
        btn_limpiar = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_porcentaje = new javax.swing.JButton();
        btn_dividir = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_multiplicar = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_menos = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_mas = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_mas_menos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(249, 240, 243));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(418, 680));
        setMinimumSize(new java.awt.Dimension(418, 680));
        setPreferredSize(new java.awt.Dimension(418, 680));
        setResizable(false);

        panel_1.setBackground(new java.awt.Color(249, 240, 243));
        panel_1.setMaximumSize(new java.awt.Dimension(420, 200));
        panel_1.setMinimumSize(new java.awt.Dimension(420, 200));
        panel_1.setPreferredSize(new java.awt.Dimension(420, 200));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 40)); // NOI18N
        lbl_titulo.setText("Estándar");

        lbl_operacion.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        lbl_operacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_operacion.setText("0");
        lbl_operacion.setMaximumSize(new java.awt.Dimension(400, 30));
        lbl_operacion.setMinimumSize(new java.awt.Dimension(400, 30));
        lbl_operacion.setPreferredSize(new java.awt.Dimension(400, 30));

        lbl_resultado.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        lbl_resultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbl_resultado.setText("0");
        lbl_resultado.setMaximumSize(new java.awt.Dimension(400, 30));
        lbl_resultado.setMinimumSize(new java.awt.Dimension(400, 30));
        lbl_resultado.setPreferredSize(new java.awt.Dimension(400, 30));

        tb_claro_oscuro.setBackground(new java.awt.Color(249, 240, 243));
        tb_claro_oscuro.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        tb_claro_oscuro.setText("Claro☀");
        tb_claro_oscuro.setBorder(null);
        tb_claro_oscuro.setFocusPainted(false);
        tb_claro_oscuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_claro_oscuroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_1Layout = new javax.swing.GroupLayout(panel_1);
        panel_1.setLayout(panel_1Layout);
        panel_1Layout.setHorizontalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tb_claro_oscuro)
                    .addGroup(panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_1Layout.setVerticalGroup(
            panel_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tb_claro_oscuro, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(lbl_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panel_2.setBackground(new java.awt.Color(249, 240, 243));
        panel_2.setMaximumSize(new java.awt.Dimension(420, 400));
        panel_2.setMinimumSize(new java.awt.Dimension(420, 400));
        panel_2.setPreferredSize(new java.awt.Dimension(420, 400));

        btn_limpiar.setBackground(new java.awt.Color(251, 247, 250));
        btn_limpiar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_limpiar.setText("C");
        btn_limpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_limpiar.setBorderPainted(false);
        btn_limpiar.setFocusPainted(false);
        btn_limpiar.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_limpiar.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_limpiar.setOpaque(true);
        btn_limpiar.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_borrar.setBackground(new java.awt.Color(251, 247, 250));
        btn_borrar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_borrar.setText("←");
        btn_borrar.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_borrar.setBorderPainted(false);
        btn_borrar.setFocusPainted(false);
        btn_borrar.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_borrar.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_borrar.setOpaque(true);
        btn_borrar.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_porcentaje.setBackground(new java.awt.Color(251, 247, 250));
        btn_porcentaje.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_porcentaje.setText("%");
        btn_porcentaje.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_porcentaje.setBorderPainted(false);
        btn_porcentaje.setFocusPainted(false);
        btn_porcentaje.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_porcentaje.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_porcentaje.setOpaque(true);
        btn_porcentaje.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_porcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_porcentajeActionPerformed(evt);
            }
        });

        btn_dividir.setBackground(new java.awt.Color(251, 247, 250));
        btn_dividir.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_dividir.setText("÷");
        btn_dividir.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_dividir.setBorderPainted(false);
        btn_dividir.setFocusPainted(false);
        btn_dividir.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_dividir.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_dividir.setOpaque(true);
        btn_dividir.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_dividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dividirActionPerformed(evt);
            }
        });

        btn_7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_7.setText("7");
        btn_7.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_7.setBorderPainted(false);
        btn_7.setFocusPainted(false);
        btn_7.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_7.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_7.setOpaque(true);
        btn_7.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_8.setText("8");
        btn_8.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_8.setBorderPainted(false);
        btn_8.setFocusPainted(false);
        btn_8.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_8.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_8.setOpaque(true);
        btn_8.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_9.setText("9");
        btn_9.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_9.setBorderPainted(false);
        btn_9.setFocusPainted(false);
        btn_9.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_9.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_9.setOpaque(true);
        btn_9.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_multiplicar.setBackground(new java.awt.Color(251, 247, 250));
        btn_multiplicar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_multiplicar.setText("x");
        btn_multiplicar.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_multiplicar.setBorderPainted(false);
        btn_multiplicar.setFocusPainted(false);
        btn_multiplicar.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_multiplicar.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_multiplicar.setOpaque(true);
        btn_multiplicar.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicarActionPerformed(evt);
            }
        });

        btn_4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_4.setText("4");
        btn_4.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_4.setBorderPainted(false);
        btn_4.setFocusPainted(false);
        btn_4.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_4.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_4.setOpaque(true);
        btn_4.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_5.setText("5");
        btn_5.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_5.setBorderPainted(false);
        btn_5.setFocusPainted(false);
        btn_5.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_5.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_5.setOpaque(true);
        btn_5.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_6.setText("6");
        btn_6.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_6.setBorderPainted(false);
        btn_6.setFocusPainted(false);
        btn_6.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_6.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_6.setOpaque(true);
        btn_6.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_menos.setBackground(new java.awt.Color(251, 247, 250));
        btn_menos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_menos.setText("-");
        btn_menos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_menos.setBorderPainted(false);
        btn_menos.setFocusPainted(false);
        btn_menos.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_menos.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_menos.setOpaque(true);
        btn_menos.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menosActionPerformed(evt);
            }
        });

        btn_1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_1.setText("1");
        btn_1.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_1.setBorderPainted(false);
        btn_1.setFocusPainted(false);
        btn_1.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_1.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_1.setOpaque(true);
        btn_1.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_2.setText("2");
        btn_2.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_2.setBorderPainted(false);
        btn_2.setFocusPainted(false);
        btn_2.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_2.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_2.setOpaque(true);
        btn_2.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_3.setText("3");
        btn_3.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_3.setBorderPainted(false);
        btn_3.setFocusPainted(false);
        btn_3.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_3.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_3.setOpaque(true);
        btn_3.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_mas.setBackground(new java.awt.Color(251, 247, 250));
        btn_mas.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_mas.setText("+");
        btn_mas.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_mas.setBorderPainted(false);
        btn_mas.setFocusPainted(false);
        btn_mas.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_mas.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_mas.setOpaque(true);
        btn_mas.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masActionPerformed(evt);
            }
        });

        btn_punto.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_punto.setText(".");
        btn_punto.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_punto.setBorderPainted(false);
        btn_punto.setFocusPainted(false);
        btn_punto.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_punto.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_punto.setOpaque(true);
        btn_punto.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(0, 159, 170));
        btn_igual.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_igual.setText("=");
        btn_igual.setBorder(null);
        btn_igual.setBorderPainted(false);
        btn_igual.setFocusPainted(false);
        btn_igual.setFocusable(false);
        btn_igual.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_igual.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_igual.setOpaque(true);
        btn_igual.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_0.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_0.setText("0");
        btn_0.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_0.setBorderPainted(false);
        btn_0.setFocusPainted(false);
        btn_0.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_0.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_0.setOpaque(true);
        btn_0.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_mas_menos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        btn_mas_menos.setText("±");
        btn_mas_menos.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        btn_mas_menos.setBorderPainted(false);
        btn_mas_menos.setFocusPainted(false);
        btn_mas_menos.setMaximumSize(new java.awt.Dimension(91, 70));
        btn_mas_menos.setMinimumSize(new java.awt.Dimension(91, 70));
        btn_mas_menos.setOpaque(true);
        btn_mas_menos.setPreferredSize(new java.awt.Dimension(91, 70));
        btn_mas_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mas_menosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_2Layout = new javax.swing.GroupLayout(panel_2);
        panel_2.setLayout(panel_2Layout);
        panel_2Layout.setHorizontalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_2Layout.createSequentialGroup()
                        .addComponent(btn_mas_menos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_2Layout.setVerticalGroup(
            panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_porcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_menos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_mas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_mas_menos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenuBar1.setBorder(null);
        jMenuBar1.setFocusable(false);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuBar1.setInheritsPopupMenu(true);
        jMenuBar1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(418, 45));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(418, 45));
        jMenuBar1.setOpaque(true);
        jMenuBar1.setPreferredSize(new java.awt.Dimension(418, 45));

        jMenu1.setText("Opciones");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel_2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btn_limpiarActionPerformed
 
    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_porcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_porcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_porcentajeActionPerformed

    private void btn_dividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dividirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dividirActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menosActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_masActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_mas_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mas_menosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mas_menosActionPerformed

    private void btn_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_multiplicarActionPerformed

    private void tb_claro_oscuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_claro_oscuroActionPerformed
       if (tb_claro_oscuro.isSelected()) {
        tb_claro_oscuro.setText("Oscuro 🌙");
        tb_claro_oscuro.setForeground(Color.WHITE);
        panel_1.setBackground(new Color(0x221f20));
        panel_2.setBackground(new Color(0x221f20));
        lbl_titulo.setForeground(Color.WHITE);
        lbl_operacion.setForeground(Color.WHITE);
        lbl_resultado.setForeground(Color.WHITE);
        
        btn_1.setBackground(new Color(0x3f393b));
        btn_1.setForeground(Color.WHITE);
        btn_2.setBackground(new Color(0x3f393b));
        btn_2.setForeground(Color.WHITE);
        btn_3.setBackground(new Color(0x3f393b));
        btn_3.setForeground(Color.WHITE);
        btn_4.setBackground(new Color(0x3f393b));
        btn_4.setForeground(Color.WHITE);
        btn_5.setBackground(new Color(0x3f393b));
        btn_5.setForeground(Color.WHITE);
        btn_6.setBackground(new Color(0x3f393b));
        btn_6.setForeground(Color.WHITE);
        btn_7.setBackground(new Color(0x3f393b));
        btn_7.setForeground(Color.WHITE);
        btn_8.setBackground(new Color(0x3f393b));
        btn_8.setForeground(Color.WHITE);
        btn_9.setBackground(new Color(0x3f393b));
        btn_9.setForeground(Color.WHITE);
        btn_0.setBackground(new Color(0x3f393b));
        btn_0.setForeground(Color.WHITE);
        btn_mas_menos.setBackground(new Color(0x3f393b));
        btn_mas_menos.setForeground(Color.WHITE);
        btn_punto.setBackground(new Color(0x3f393b));
        btn_punto.setForeground(Color.WHITE);
        
        btn_limpiar.setBackground(new Color(0x333133));
        btn_limpiar.setForeground(Color.WHITE);
        btn_borrar.setBackground(new Color(0x333133));
        btn_borrar.setForeground(Color.WHITE);
        btn_porcentaje.setBackground(new Color(0x333133));
        btn_porcentaje.setForeground(Color.WHITE);
        btn_dividir.setBackground(new Color(0x333133));
        btn_dividir.setForeground(Color.WHITE);
        btn_multiplicar.setBackground(new Color(0x333133));
        btn_multiplicar.setForeground(Color.WHITE);
        btn_menos.setBackground(new Color(0x333133));
        btn_menos.setForeground(Color.WHITE);
        btn_mas.setBackground(new Color(0x333133));
        btn_mas.setForeground(Color.WHITE);
        
        btn_igual.setBackground(new Color(0x29f7ff));
        btn_igual.setForeground(Color.WHITE);
      
    } else {
        tb_claro_oscuro.setText("Claro ☀"); 
        tb_claro_oscuro.setForeground(Color.BLACK);
        panel_1.setBackground(new Color(0xF9F0F3));
        panel_2.setBackground(new Color(0xF9F0F3));
        lbl_titulo.setForeground(Color.BLACK);
        lbl_operacion.setForeground(Color.BLACK);
        lbl_resultado.setForeground(Color.BLACK);
        
        
        btn_1.setBackground(new Color(0xFFFFFF));
        btn_1.setForeground(Color.BLACK);
        btn_2.setBackground(new Color(0xFFFFFF));
        btn_2.setForeground(Color.BLACK);
        btn_3.setBackground(new Color(0xFFFFFF));
        btn_3.setForeground(Color.BLACK);
        btn_4.setBackground(new Color(0xFFFFFF));
        btn_4.setForeground(Color.BLACK);
        btn_5.setBackground(new Color(0xFFFFFF));
        btn_5.setForeground(Color.BLACK);
        btn_6.setBackground(new Color(0xFFFFFF));
        btn_6.setForeground(Color.BLACK);
        btn_7.setBackground(new Color(0xFFFFFF));
        btn_7.setForeground(Color.BLACK);
        btn_8.setBackground(new Color(0xFFFFFF));
        btn_8.setForeground(Color.BLACK);
        btn_9.setBackground(new Color(0xFFFFFF));
        btn_9.setForeground(Color.BLACK);
        btn_0.setBackground(new Color(0xFFFFFF));
        btn_0.setForeground(Color.BLACK);
        btn_mas_menos.setBackground(new Color(0xFFFFFF));
        btn_mas_menos.setForeground(Color.BLACK);
        btn_punto.setBackground(new Color(0xFFFFFF));
        btn_punto.setForeground(Color.BLACK);
        
        btn_limpiar.setBackground(new Color(0xFBF7FA));
        btn_limpiar.setForeground(Color.BLACK);
        btn_borrar.setBackground(new Color(0xFBF7FA));
        btn_borrar.setForeground(Color.BLACK);
        btn_porcentaje.setBackground(new Color(0xFBF7FA));
        btn_porcentaje.setForeground(Color.BLACK);
        btn_dividir.setBackground(new Color(0xFBF7FA));
        btn_dividir.setForeground(Color.BLACK);
        btn_multiplicar.setBackground(new Color(0xFBF7FA));
        btn_multiplicar.setForeground(Color.BLACK);
        btn_menos.setBackground(new Color(0xFBF7FA));
        btn_menos.setForeground(Color.BLACK);
        btn_mas.setBackground(new Color(0xFBF7FA));
        btn_mas.setForeground(Color.BLACK);
        
        btn_igual.setBackground(new Color(0x009FAA));
        btn_igual.setForeground(Color.WHITE);
        
    }
    }//GEN-LAST:event_tb_claro_oscuroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the System look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    try {
        javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(interfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        new interfazCalculadora().setVisible(true);
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_dividir;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_mas;
    private javax.swing.JButton btn_mas_menos;
    private javax.swing.JButton btn_menos;
    private javax.swing.JButton btn_multiplicar;
    private javax.swing.JButton btn_porcentaje;
    private javax.swing.JButton btn_punto;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_operacion;
    private javax.swing.JLabel lbl_resultado;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel panel_1;
    private javax.swing.JPanel panel_2;
    private javax.swing.JToggleButton tb_claro_oscuro;
    // End of variables declaration//GEN-END:variables
}
